# Automatically updated by the winget bot at 2021/May/25
PackageIdentifier: DigiDNA.iMazing
PackageVersion: 2.13.8.0
PackageName: iMazing
Publisher: DigiDNA
License: Copyright (c) DigiDNA SARL
Tags:
- iphone
- ipad
- ipod
- ios
- manager
- backup
ShortDescription: iMazing lets you transfer music, files, messages, apps and more from any iPhone, iPad, or iPod to a computer, Mac or PC. Manage and backup your iOS device simply without iTunes. (was DiskAid)
PackageUrl: https://imazing.com/
Installers:
- Architecture: x64
  InstallerUrl: https://downloads.imazing.com/windows/iMazing/iMazing2forWindows.exe
  InstallerSha256: 92D4C349B91447F0E6603F83BC16EA8199241C9240D18401A21C1F98E7C11746
  InstallerType: inno
  InstallerSwitches:
    Silent: /VERYSILENT /NORESTART
    SilentWithProgress: /SILENT /NORESTART
PackageLocale: en-US
ManifestType: singleton
ManifestVersion: 1.0.0
