# Automatically updated by the winget bot at 2021/May/22
PackageIdentifier: Blitz.Blitz
Publisher: Blitz
PackageName: Blitz
PackageVersion: 1.14.17.511
License: Custom use license
InstallerType: exe
LicenseUrl: https://www.blitz.gg/terms-of-service
Moniker: blitz.gg
Tags:
- lol
- blitz
- league
- legends
ShortDescription: Blitz App - Your personal gaming coach
PackageUrl: https://blitz.gg/
Installers:
- Architecture: x86
  InstallerType: exe
  InstallerUrl: https://blitz.gg/download/win
  InstallerSha256: 68321EF40EB580EC1911731A65597DB3E430652359675BE64972274229F8EBF6
PackageLocale: en-US
ManifestType: singleton
ManifestVersion: 1.0.0
