# Automatically updated by the winget bot at 2021/May/18
PackageIdentifier: Huawei.Welink
PackageName: Welink
PackageVersion: 7.5.24
Publisher: Huawei
License: copyright (c) Huawei
LicenseUrl: https://www.huaweicloud.com/declaration/statement.html#
PackageUrl: https://www.huaweicloud.com/product/welink-download.html
ShortDescription: A unified communication and collaboration platform that combines persistent workplace chat and video meetings.
Tags:
- huawei
- meeting
- video
- work
- cloud
- collaboration
- electron
InstallerType: inno
Installers:
- Architecture: x64
  InstallerUrl: https://welink.huaweicloud.com/download/WeLink_setup.exe
  InstallerSha256: CED0834A44F754CB36DFB1766E7FF0E0C10077529AEADB611B8F3B31E45F76E1
PackageLocale: en-US
ManifestType: singleton
ManifestVersion: 1.0.0
