# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultlocale.1.0.0.schema.json
PackageIdentifier: Azul.Zulu.11
PackageVersion: 11.0.11
PackageLocale: en-US
Publisher: Azul
PublisherUrl: https://www.azul.com/
Author: Azul
PackageName: Azul Zulu 11
PackageUrl: https://www.azul.com/downloads/
License: GPL-2.0-only WITH Classpath-exception-2.0
LicenseUrl: https://www.azulsystems.com/license/zulu_third_party_licenses.html
ShortDescription: Zulu 11 is a build of OpenJDK 11
Moniker: azulzulu-openjdk-11
Tags:
  - Java
ManifestType: defaultLocale
ManifestVersion: 1.0.0
