# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.0.0.schema.json
PackageIdentifier: RARLab.WinRARBeta
PackageVersion: 6.02.1
MinimumOSVersion: 10.0.0.0
FileExtensions:
  - RAR
  - ZIP
  - 7Z
  - ARJ
  - BZ2
  - CAB
  - GZ
  - ISO
  - JAR
  - LZ
  - LZH
  - TAR
  - UUE
  - XZ
  - Z
  - ZIPX
  - 001
Commands:
  - winrar
InstallModes:
  - interactive
  - silent
  - silentWithProgress
InstallerSwitches:
  Silent: /S
  SilentWithProgress: /S
Scope: machine
UpgradeBehavior: install
InstallerType: exe
Installers:
  - Architecture: x64
    InstallerType: exe
    InstallerUrl: https://www.rarlab.com/rar/winrar-x64-602b1.exe
    InstallerSha256: 4e959e3fe8043e80ec12247a1c85af31016ffe5634a1d6f021555b4882b1efc4
    InstallerLocale: en-US
  - Architecture: x86
    InstallerUrl: https://www.rarlab.com/rar/wrar602b1.exe
    InstallerSha256: 2040aa160712d86b9f49f0bce3a577227b6654ab6f3a901353ad53d84ea1193f
    InstallerLocale: en-US
ManifestType: installer
ManifestVersion: 1.0.0
