PackageIdentifier: PrimateLabs.Geekbench
PackageVersion: 5.4.1
PackageName: Geekbench
Publisher: Primate Labs
License: © 2004-2019 Primate Labs Inc.
Moniker: geekbench
Tags:
- benchmark
- geekbench
ShortDescription: Cross-Platform Benchmark
PackageUrl: https://www.geekbench.com/
Installers:
- Architecture: x64
  InstallerUrl: https://cdn.geekbench.com/Geekbench-5.4.1-WindowsSetup.exe
  InstallerSha256: 0eec12ad0cf91a4f9cb28f8e39b82357ed86b501ce44386ed90a4e7d02e6294a
  InstallerType: exe
  InstallerSwitches:
    Silent: "/S"
    SilentWithProgress: "/S"
PackageLocale: en-US
ManifestType: singleton
ManifestVersion: 1.0.0
