PackageIdentifier: TopalaSoftwareSolutions.SIW
Publisher: Topala Software Solutions
PackageName: System Information for Windows
Moniker: siw
MinimumOSVersion: 6.1.0.0
PackageVersion: 2021.05.26.0
ShortDescription: System Information for Windows - Everything you want to know about your computer
License: Commercial
LicenseUrl: https://www.gtopala.com/agreement/
PackageUrl: https://www.gtopala.com/
Installers:
- Architecture: neutral
  InstallerUrl: https://siw64.com/download/siwtrial-setup.exe
  InstallerSha256: BF1690719E807D32763DB02DFE2C373749C3B4673CF9488E5B48C1AB97F999A5
  InstallerType: inno
  InstallerSwitches:
    Silent: /VERYSILENT
    SilentWithProgress: /VERYSILENT
PackageLocale: en-US
ManifestType: singleton
ManifestVersion: 1.0.0
