PackageIdentifier: LutzRoeder.Netron
PackageVersion: 4.9.4
PackageName: Netron
Publisher: Lutz Roeder
Moniker: netron
ShortDescription: Visualizer for neural network, deep learning, and machine learning models
License: Copyright (c) Lutz Roeder
PackageUrl: https://github.com/lutzroeder/netron
Installers:
- Architecture: x86
  InstallerType: nullsoft
  InstallerUrl: https://github.com/lutzroeder/netron/releases/download/v4.9.4/Netron-Setup-4.9.4.exe
  InstallerSha256: 1CE0B57342D7549BDEDD2379B991C54F1377642110207224533B3F263754C789
PackageLocale: en-US
ManifestType: singleton
ManifestVersion: 1.0.0
