# Automatically updated by the winget bot at 2021/May/21
PackageIdentifier: ProtonTechnologies.ProtonMailBridge
Publisher: Proton Technologies
PackageName: ProtonMail Bridge
PackageVersion: 1.8.2
Moniker: protonmailbridge
ShortDescription: A bridge for paid ProtonMail users to encrypt and decrypt mail from a local mail client
PackageUrl: https://protonmail.com/bridge/
Tags:
- email
- imap
- smtp
License: Copyright (c) Proton Technologies AG
InstallerSwitches:
  Silent: /qn
  SilentWithProgress: /qb
InstallerType: exe
Installers:
- Architecture: x64
  InstallerUrl: https://protonmail.com/download/Bridge-Installer.exe
  InstallerSha256: D8F1AE5D4716AB90817F558DB1C48C55182DA798E9F05CCAC3529CB3A6DA842F
PackageLocale: en-US
ManifestType: singleton
ManifestVersion: 1.0.0
