# Automatically updated by the winget bot at 2021/May/25
PackageIdentifier: Microsoft.VC++2015-2019Redist-x64
PackageVersion: 14.29.30037.0
PackageName: Microsoft Visual C++ 2015-2019 Redistributable (x64)
Publisher: Microsoft Corporation
Author: Microsoft
PackageUrl: https://support.microsoft.com/help/2977003/the-latest-supported-visual-c-downloads
License: Copyright (c) Microsoft Corporation
Tags:
- visual c++
- redist
ShortDescription: Microsoft.VC++2015-2019Redist-x64
Description: The Microsoft Visual C++ 2015-2019 Redistributable Package (x64) installs runtime components of Visual C++ Libraries required to run 64-bit applications developed with Visual C++ 2015, 2017 and 2019 on a computer that does not have Visual C++ 2015, 2017 and 2019 installed.
Installers:
- Architecture: x64
  InstallerUrl: https://aka.ms/vs/16/release/vc_redist.x64.exe
  InstallerSha256: A1592D3DA2B27230C087A3B069409C1E82C2664B0D4C3B511701624702B2E2A3
  InstallerType: exe
  InstallerSwitches:
    Silent: /quiet /install /norestart
    SilentWithProgress: /passive /install /norestart
  InstallerSuccessCodes:
    - 3010
PackageLocale: en-US
ManifestType: singleton
ManifestVersion: 1.0.0
