PackageIdentifier: EpicGames.EpicGamesLauncher
PackageVersion: 1.2.17.0
PackageName: Epic Games Launcher
Publisher: Epic Games Inc.
License: Epic Games Store End User License
LicenseUrl: https://www.epicgames.com/store/en-US/eula
Moniker: egs
Tags:
- store
ShortDescription: Epic Games Launcher for the Epic Games Store and Unreal Engine
PackageUrl: https://www.epicgames.com/store
InstallerType: msi
Installers:
- Architecture: x64
  InstallerUrl: https://epicgames-download1.akamaized.net/Builds/UnrealEngineLauncher/Installers/Win32/EpicInstaller-12.1.7.msi
  InstallerSha256: 6b069ab06ac7f0885b17214980b1ced6bfec5311d44cd510ef884ca5bf516aa1
PackageLocale: en-US
ManifestType: singleton
ManifestVersion: 1.0.0
