PackageIdentifier: z-------------.cpod
Publisher: z-------------
PackageName: CPod
Author: z-------------
ShortDescription: A simple, beautiful podcast app for Windows, macOS, and Linux.
Moniker: cumulonimbus
Tags:
- electron
- podcast
- audio
PackageUrl: https://github.com/z-------------/CPod
License: Apache2.0
LicenseUrl: https://github.com/z-------------/CPod/blob/master/LICENSE
PackageVersion: 1.27.1
InstallerType: nullsoft
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/z-------------/CPod/releases/download/v1.27.1/CPod-Setup-1.27.1.exe
  InstallerSha256: 11d1409626e606ebf6097f313d6541d5b26622ebe3aaa2f1c02c31911cdaa1cd
PackageLocale: en-US
ManifestType: singleton
ManifestVersion: 1.0.0
