# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultlocale.1.0.0.schema.json
PackageIdentifier: Microsoft.dotnetPreview
PackageVersion: 6.0.100-preview.4.21255.9
PackageLocale: en-US
Publisher: Microsoft
#PublisherUrl: 
#PublisherSupportUrl: 
#PrivacyUrl: 
#Author: 
PackageName: .NET SDK Preview
PackageUrl: https://docs.microsoft.com/dotnet
License: MIT
LicenseUrl: https://github.com/dotnet/core/blob/master/LICENSE.TXT
#Copyright: 
#CopyrightUrl: 
ShortDescription: Preview version of the .NET SDK.
#Description: 
Moniker: dotnet-preview
ManifestType: defaultLocale
ManifestVersion: 1.0.0
