# Automatically updated by the winget bot at 2021/May/17
PackageIdentifier: TunnelBear.TunnelBear
PackageVersion: 4.4.3.0
PackageName: TunnelBear
Publisher: TunnelBear
License: Copyright TunnelBear
Moniker: tunnelbear
Tags:
- vpn
ShortDescription: Public VPN Service
PackageUrl: https://www.tunnelbear.com/
Installers:
- Architecture: x86
  InstallerUrl: https://tunnelbear.s3.amazonaws.com/downloads/pc/public/TunnelBear-Installer.exe
  InstallerSha256: A86DAFAA8A90C906A7C12D2035BC77B914C4695F3A4DF9EF63C2A8707C94D2F0
  InstallerType: exe
  InstallerSwitches:
    Silent: "-s"
    SilentWithProgress: "-s"
PackageLocale: en-US
ManifestType: singleton
ManifestVersion: 1.0.0
