# yaml-language-server: $schema=https://aka.ms/winget-manifest.singleton.1.0.0.schema.json
PackageIdentifier: Microsoft.AzureDataStudio
PackageVersion: 1.29.0
PackageName: Azure Data Studio
Moniker: azuredatastudio
Publisher: Microsoft Corporation
Author: Microsoft Corporation
PackageUrl: https://docs.microsoft.com/en-us/sql/azure-data-studio/what-is-azure-data-studio
License: Copyright (C) Microsoft Corporation
ShortDescription: Azure Data Studio is a data management tool that enables you to work with SQL Server, Azure SQL DB and SQL DW from Windows, macOS and Linux.
Tags:
- sql
- azure
- mssql
- postgres
- mysql
Installers:
- Architecture: x64
  InstallerUrl: https://sqlopsbuilds.azureedge.net/stable/0f5cfdc2c8c2433028842e16dc5ac1a65da24292/azuredatastudio-windows-setup-1.29.0.exe
  InstallerType: inno
  InstallerSha256: 5242ffc3bd3e31b44e3d3357bd994551d3aba613a9dc740063362d6ff65a83d6
  Scope: user
PackageLocale: en-US
ManifestType: singleton
ManifestVersion: 1.0.0

