PackageIdentifier: VMware.WorkstationPlayer
PackageName: VMware Workstation Player
Moniker: vmware-workstation-player
PackageVersion: 16.1.2
Publisher: VMware, Inc.
Author: VMware, Inc.
License: (c) 2021 VMware, Inc.
LicenseUrl: https://www.vmware.com/help/legal.html
ShortDescription: VMware.WorkstationPlayer
Description: VMware Workstation Player allows you to run a second, isolated operating system on a single PC. With many uses ranging from a personal educational tool, to a business tool for providing a simplified experience to run a corporate desktop on a BYO device, Workstation Player leverages the VMware vSphere Hypervisor to provide a simple yet mature and stable, local virtualization solution.
PackageUrl: https://www.vmware.com/products/workstation-player.html
Installers:
- Architecture: x64
  InstallerUrl: https://download3.vmware.com/software/player/file/VMware-player-16.1.2-17966106.exe
  InstallerSha256: ce5949c2ca89c6fc8349d63e6d1dd053325b5803b93870aa3b73a106d76c942f
  InstallerType: exe
  InstallerSwitches:
    Silent: /s /v /q EULAS_AGREED=1
    SilentWithProgress: /s /v /q EULAS_AGREED=1
PackageLocale: en-US
ManifestType: singleton
ManifestVersion: 1.0.0
