# Automatically updated by the winget bot at 2021/May/22
PackageIdentifier: NimbusWeb.NimbusWeb
PackageName: NimbusWeb
Moniker: NimbusWeb
PackageVersion: 6.38.8
Publisher: NimbusWeb
License: Copyright (C) 2020 NimbusWeb
LicenseUrl: https://nimbusweb.me/terms-and-conditions.php
MinimumOSVersion: 10.0.0.0
PackageUrl: https://nimbusweb.me
ShortDescription: Transform information chaos from multiple sources into an organized workplace.
Tags:
- nimbus web
- nimbus note
Installers:
- Architecture: x64
  InstallerUrl: https://nimbusweb.me/nimbusnote.exe
  InstallerType: exe
  InstallerSha256: 673302823011877437E62934D19A0204E881972FD29ED4DC27ABFB3C354B6FA3
  InstallerSwitches:
    Silent: /S
    SilentWithProgress: /S
PackageLocale: en-US
ManifestType: singleton
ManifestVersion: 1.0.0
