# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.0.0.schema.json
PackageIdentifier: LINE.LINE
PackageVersion: 7.0.0.2534
MinimumOSVersion: 10.0.0.0
InstallModes:
  - interactive
  - silent
  - silentWithProgress
Installers:
  - Architecture: neutral
    InstallerType: exe
    InstallerUrl: https://desktop.line-scdn.net/win/new/LineInst.exe
    InstallerSha256: 48449DF38DE95B737D1DEE8008EB472EE907B15358EB3316450D211AC0D4B781
    InstallerSwitches:
      Silent: /M
      SilentWithProgress: /M
    Scope: user
    InstallerLocale: en-US
    UpgradeBehavior: install
ManifestType: installer
ManifestVersion: 1.0.0
