# Automatically updated by the winget bot at 2021/May/24
PackageIdentifier: Cisco.WebexTeams
PackageVersion: 41.5.0.18911
InstallerType: msi
Installers:
- Architecture: x64
  InstallerType: msi
  InstallerUrl: https://binaries.webex.com/WebexTeamsDesktop-Windows-Gold/Webex.msi
  InstallerSha256: 6BE89351F25C1CE2DE2503CB5F2CBF6E13DFC45C9A7AC65ACD0A9BD19D3828EF
  ProductCode: "{5CB4E676-869D-52F8-A498-9A525C2ABCD3}"
- Architecture: x86
  InstallerType: msi
  InstallerUrl: https://binaries.webex.com/WebexTeamsDesktop-Windows-Gold/Webex_x86.msi
  InstallerSha256: 36E29909E9F36223103B65086ED125769727DD7AAAEB9D9A86A7836C1F90465E
  ProductCode: "{9FAD5FD8-0715-57C2-92EE-5CD5084592D7}"
ManifestType: installer
ManifestVersion: 1.0.0
