PackageIdentifier: SQLiteBrowser.SQLiteBrowser
PackageVersion: 3.12.2
PackageName: DB Browser for SQLite
Publisher: SQLiteBrowser
License: GNU GPL 3
LicenseUrl: https://github.com/sqlitebrowser/sqlitebrowser/blob/master/LICENSE
Moniker: sqlitebrowser
Tags:
- sqlite
- dbbrowser
- database
ShortDescription: DB Browser for SQLite (DB4S) is a high quality, visual, open source tool to create, design, and edit database files compatible with SQLite.
PackageUrl: https://sqlitebrowser.org/
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/sqlitebrowser/sqlitebrowser/releases/download/v3.12.2/DB.Browser.for.SQLite-3.12.2-win64.msi
  InstallerSha256: 723d601f125b0d2402d9ea191e4b310345ec52f76b61e117bf49004a2ff9b8ae
  ProductCode: "{E6668432-CAB0-416D-9422-E24C9E71DB68}"
  InstallerType: msi
  InstallerSwitches:
    Custom: "SHORTCUT_SQLITE_DESKTOP=1 SHORTCUT_SQLCIPHER_DESKTOP=1 SHORTCUT_SQLITE_PROGRAMMENU=1 SHORTCUT_SQLCIPHER_PROGRAMMENU=1"
PackageLocale: en-US
ManifestType: singleton
ManifestVersion: 1.0.0
