# Automatically updated by the winget bot at 2021/May/20
PackageIdentifier: Figma.Figma
PackageVersion: 98.10.0
PackageName: Figma
Publisher: Figma Inc
License: Copyright (c) Figma Inc
Moniker: figma
ShortDescription: The collaborative interface design tool Build better products as a team. Design, prototype, and gather feedback all in one place with Figma.
PackageUrl: https://www.figma.com/
Installers:
- Architecture: neutral
  InstallerUrl: https://desktop.figma.com/win/FigmaSetup.exe
  InstallerSha256: 2779EA1227004928759300A21F0D602913BEE728FA60414C5D9F40AD67CC36F1
  InstallerType: exe
PackageLocale: en-US
ManifestType: singleton
ManifestVersion: 1.0.0
