# Automatically updated by the winget bot at 2021/May/22
PackageIdentifier: Belarc.Advisor
PackageVersion: 9.7.0.0
PackageName: Advisor
Publisher: Belarc
License: Copyright (c) Belarc Inc.
Moniker: advisor
Tags:
- advisor
- belarc
- benchmark
- info
- profile
- profiling
ShortDescription: The Belarc Advisor builds a detailed profile of your installed software and hardware, network inventory, any missing Microsoft hotfixes, anti-virus status, security benchmarks, and displays the results in your Web browser.
Installers:
- Architecture: x86
  InstallerUrl: https://downloads.belarc.com/advisor/advisorinstaller.exe
  InstallerSha256: C091FACD2C59E3C70AF408666E86D93AE42A2904ECB7ED932297C7FF2F1EB840
  InstallerType: exe
  InstallerSwitches:
    Silent: /s
    SilentWithProgress: /s
PackageLocale: en-US
ManifestType: singleton
ManifestVersion: 1.0.0
