# yaml-language-server: $schema=https://aka.ms/winget-manifest.singleton.1.0.0.schema.json
PackageIdentifier: KDE.KDEConnect
PackageVersion: 21.04.1.597
PackageName: KDE Connect
Publisher: KDE
License: GNU GPLv2/GNU GPLv3
LicenseUrl: https://www.gnu.org/licenses/gpl-2.0.html
Moniker: kdeconnect
Tags:
- android
- phone
- connect
- kde
- k
ShortDescription: Enabling communication between all your devices. Made for people like you.
PackageUrl: https://kdeconnect.kde.org/
Installers:
- Architecture: x64
  InstallerUrl: https://binary-factory.kde.org/job/kdeconnect-kde_Release_win64/lastSuccessfulBuild/artifact/kdeconnect-kde-21.04.1-597-windows-msvc2019_64-cl.exe
  InstallerSha256: 57054FC1C415F8650CD382157C03DF44575DBDC846B153A8FF05D9AC181BB822
  InstallerType: exe
  InstallerSwitches:
    Silent: /S
    SilentWithProgress: /S
PackageLocale: en-US
ManifestType: singleton
ManifestVersion: 1.0.0

