PackageIdentifier: TimKosse.FileZillaClientNightly
PackageName: FileZilla Client Nightly
Moniker: filezilla-nightly
PackageVersion: 3.54.1-20210524
Publisher: Tim Kosse
Author: Tim Kosse
License: (c) 2021 Tim Kosse
LicenseUrl: https://filezilla-project.org/license.php
ShortDescription: FileZilla Client is a fast and reliable cross-platform FTP, FTPS and SFTP client with lots of useful features and an intuitive graphical user interface.
PackageUrl: https://filezilla-project.org/
Installers:
- Architecture: x64
  InstallerUrl: https://filezilla-project.org/nightlies/2021-05-24/win64/FileZilla_3_setup.exe
  InstallerSha256: d18be4a8e99734901c8214e102bdff784785d203eb0712ea8dacd30699092c87
  InstallerType: nullsoft
PackageLocale: en-US
ManifestType: singleton
ManifestVersion: 1.0.0
