# Automatically updated by the winget bot at 2021/May/20
PackageIdentifier: InTheLoop.LoopEmail
PackageName: LoopEmail
PackageVersion: 6.15.1.4468
Publisher: InTheLoop
Moniker: loopemail
License: ©2019 In the loop, All Rights Reserved.
PackageUrl: https://www.intheloop.io/
ShortDescription: Loop Email helps teams connect, collaborate and communicate all in one place.
InstallerType: exe
Installers:
- Architecture: x64
  InstallerUrl: https://dl.intheloop.io/Loop-Email-Setup.exe
  InstallerSha256: 674262CA9B27378D5584A5E5E4C363B76CD1B3D4C3E6FB0AE8FBE38B45E8DE08
  InstallerSwitches:
    Silent: /S
    SilentWithProgress: /S
PackageLocale: en-US
ManifestType: singleton
ManifestVersion: 1.0.0
