# Automatically updated by the winget bot at 2021/May/22
PackageIdentifier: xiaomi.miuiplus
Publisher: xiaomi
PackageName: miuiplus
Author: xiaomi
ShortDescription: Connect your xiaomi android phone with your windows PC
Moniker: everything
Tags:
- xiaomi
- share
- Android
- miui
- phone
- connect
PackageUrl: https://plus.miui.com/
License: copyright (c) xiaomi
LicenseUrl: https://www.miui.com/res/doc/eula/zh_CN.html
PackageVersion: 2.2.1.666
InstallerType: nullsoft
Installers:
- Architecture: x64
  InstallerUrl: https://cdn.cnbj1.fds.api.mi-img.com/core-app/milink/MiAIoT_Setup.exe
  InstallerSha256: 48933B197711DEB62A30B629DCF18C445091056CEACB30C9E3AF08EFE99AAD2B
PackageLocale: en-US
ManifestType: singleton
ManifestVersion: 1.0.0
