PackageIdentifier: Discord.DiscordDevelopment
PackageName: Discord Development
Moniker: discord-development
PackageVersion: 1.0.598
Publisher: Discord Inc.
Author: Discord Inc.
License: (c) 2021 Discord Inc.
LicenseUrl: https://discord.com/licenses
ShortDescription: Whether you’re part of a school club, gaming group, worldwide art community, or just a handful of friends that want to spend time together, Discord makes it easy to talk every day and hang out more often.
PackageUrl: https://discord.com/
Installers:
- Architecture: neutral
  InstallerUrl: https://dl-development.discordapp.net/distro/app/development/win/x86/1.0.598/DiscordDevelopmentSetup.exe
  InstallerSha256: 316ab26caee8add1dc740aadda5fc1143d48c6543caa1e184bd01c4a4fba8c15
  InstallerType: exe
  InstallerSwitches:
    Silent: /s
    SilentWithProgress: /s
PackageLocale: en-US
ManifestType: singleton
ManifestVersion: 1.0.0
