# Automatically updated by the winget bot at 2021/May/19
PackageIdentifier: GlassWire.GlassWire
PackageVersion: 2.3.318.0
PackageName: GlassWire
PackageUrl: https://www.glasswire.com/download/
Author: Glasswire
Publisher: GlassWire
PublisherUrl: https://www.glasswire.com/
PublisherSupportUrl: https://www.glasswire.com/help/
PrivacyUrl: https://www.glasswire.com/privacy/
License: © 2021 GlassWire
LicenseUrl: https://www.glasswire.com/license/
ShortDescription: GlassWire is a modern personal firewall and network monitor.
Moniker: glasswire
Tags:
- firewall
- security
- privacy
MinimumOSVersion: 10.0.0.0
InstallerType: nullsoft
InstallModes:
- interactive
- silent
- silentWithProgress
Installers:
- Architecture: x64
  InstallerUrl: https://download.glasswire.com/GlassWireSetup.exe
  InstallerSha256: 5FA30D44AF5B8E4EF55044A01DDC50FC66286DB041B385FF20A3D5EEBFFE8974
  Scope: machine
  InstallerLocale: en-US
PackageLocale: en-US
ManifestType: singleton
ManifestVersion: 1.0.0
