# Automatically updated by the winget bot at 2021/May/20
PackageIdentifier: Quicken.Quicken
PackageVersion: 27.1.33.22
PackageName: Quicken
Publisher: Quicken
License: Copyright (c) Quicken Inc.
Moniker: quicken
Tags:
- quicken
- money
- qw
ShortDescription: Quicken is a personal finance management tool that can be used to record banking transactions, planning a budget and tracking investments.
PackageUrl: https://www.quicken.com
Installers:
- Architecture: x86
  InstallerUrl: https://download.quicken.com/windows/Quicken.exe
  InstallerSha256: F2CF01913610EDD19153C4BC37FF09F7F898E9863DA7491EB6A9302FBE4194FE
  InstallerType: exe
  InstallerSwitches:
    Silent: "/s /a /s"
    SilentWithProgress: "/s /a /s"
PackageLocale: en-US
ManifestType: singleton
ManifestVersion: 1.0.0
