# yaml-language-server: $schema=https://aka.ms/winget-manifest.singleton.1.0.0.schema.json
PackageName: AIMP
Publisher: AIMP
PackageIdentifier: AIMP.AIMP
PackageVersion: 4.70.2251
Moniker: aimp
Author: Artem Izmaylov, Mike Green
License: LGPLv2.1 - © Artem Izmaylov 2006-2021 | All rights reserved
MinimumOSVersion: 10.0.0.0
Tags:
- audio player
- music player
FileExtensions:
- CDA
- AAC
- AC3
- APE
- DTS
- FLAC
- IT
- MIDI
- MO3
- MOD
- M4A
- M4B
- MP1
- MP2
- MP3
- MPC
- MTM
- OFR
- OGG
- OPUS
- RMI
- S3M
- .SPX
- TAK
- TTA
- UMX
- WAV
- WMA
- WV
- XM
InstallerType: exe
ShortDescription: AIMP is a freeware audio player
PackageUrl: https://www.aimp.ru
LicenseUrl: https://www.aimp.ru/files/windows/EULA_lang-en.txt
InstallerSwitches:
  Silent: /AUTO /SILENT
  SilentWithProgress: /AUTO
Installers:
- Architecture: x86
  InstallerUrl: https://aimp.su/storage/fc9f124d6753d94c19310a6b615577f6/aimp_4.70.2251.exe
  InstallerSha256: 7A65F9153984D77E16336E15D36CD75B8ADD5E76C463343A3B37A6DB239FC3B7
  Scope: machine
PackageLocale: en-US
ManifestType: singleton
ManifestVersion: 1.0.0
