PackageIdentifier: VMware.WorkstationPro
PackageName: VMware Workstation Pro
Moniker: vmware-workstation-pro
PackageVersion: 16.1.2
Publisher: VMware, Inc.
Author: VMware, Inc.
License: (c) 2021 VMware, Inc.
LicenseUrl: https://www.vmware.com/help/legal.html
ShortDescription: VMware.WorkstationPro
Description: VMware Workstation Pro is the industry standard for running multiple operating systems as virtual machines (VMs) on a single Linux or Windows PC. IT professionals, developers and businesses who build, test or demo software for any device, platform or cloud rely on Workstation Pro.
PackageUrl: https://www.vmware.com/products/workstation-pro.html
Installers:
- Architecture: x64
  InstallerUrl: https://download3.vmware.com/software/wkst/file/VMware-workstation-full-16.1.2-17966106.exe
  InstallerSha256: 71b44f2fcfde663195b833ba19f2f70d9ed21a78f9bce35cf13c7f780418a336
  InstallerType: exe
  InstallerSwitches:
    Silent: /s /v /q EULAS_AGREED=1
    SilentWithProgress: /s /v /q EULAS_AGREED=1
PackageLocale: en-US
ManifestType: singleton
ManifestVersion: 1.0.0
