# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.0.0.schema.json
PackageIdentifier: rammichael.7+TaskbarTweaker
PackageVersion: 5.11
MinimumOSVersion: 10.0.0.0
InstallModes:
  - interactive
  - silent
  - silentWithProgress
Installers:
  - Architecture: neutral
    InstallerType: nullsoft
    InstallerUrl: https://rammichael.com/downloads/7tt_setup.exe
    InstallerSha256: e1aaa1d0889d6ec9f29a7e8faf459543fce374742afb8c95d4dfb93fdb30724c
    Scope: user
    InstallerLocale: en-US
    UpgradeBehavior: install
ManifestType: installer
ManifestVersion: 1.0.0
