# Automatically updated by the winget bot at 2021/May/21
PackageIdentifier: WhatsApp.WhatsApp
PackageVersion: 2.2119.6
MinimumOSVersion: 10.0.0.0
InstallModes:
- interactive
- silent
- silentWithProgress
Installers:
- Architecture: x64
  InstallerType: exe
  InstallerUrl: https://web.whatsapp.com/desktop/windows/release/x64/WhatsAppSetup.exe
  InstallerSha256: 87C69246688D6801F0A2C184F949E039A3E3D2C988EC482C65D331D44A77224F
  InstallerSwitches:
    Silent: --silent
    SilentWithProgress: --silent
  Scope: machine
  InstallerLocale: en-US
  UpgradeBehavior: install
- Architecture: x86
  InstallerType: exe
  InstallerUrl: https://web.whatsapp.com/desktop/windows/release/ia32/WhatsAppSetup.exe
  InstallerSha256: 25BB32C132F8BD74FFB5615B40D63BDBD133F6F420A097A2C5B06EB0A551AD45
  InstallerSwitches:
    Silent: --silent
    SilentWithProgress: --silent
  Scope: machine
  InstallerLocale: en-US
  UpgradeBehavior: install
ManifestType: installer
ManifestVersion: 1.0.0
