PackageIdentifier: TimKosse.FileZillaClientNightly
PackageName: FileZilla Client Nightly
Moniker: filezilla-nightly
PackageVersion: 3.54.1-20210522
Publisher: Tim Kosse
Author: Tim Kosse
License: (c) 2021 Tim Kosse
LicenseUrl: https://filezilla-project.org/license.php
ShortDescription: FileZilla Client is a fast and reliable cross-platform FTP, FTPS and SFTP client with lots of useful features and an intuitive graphical user interface.
PackageUrl: https://filezilla-project.org/
Installers:
- Architecture: x64
  InstallerUrl: https://filezilla-project.org/nightlies/2021-05-22/win64/FileZilla_3_setup.exe
  InstallerSha256: e85be8399436cf3b3964c27cb32d80d0cb2ef643c5bcde4ba41f9d035beb1f54
  InstallerType: nullsoft
PackageLocale: en-US
ManifestType: singleton
ManifestVersion: 1.0.0
