PackageIdentifier: NetSarangComputer.PortX
PackageVersion: 1.1.1
Publisher: NetSarangComputer
PackageName: PortX
PrivacyUrl: https://www.netsarang.com/en/privacy-policy-portx/
License: Copyright © NetSarang Computer, Inc. All rights reserved.
ShortDescription: PortX aims to provide unparalleled cross-platform session management and usability
Tags:
 - iterm
 - termius
 - ssh
 - putty
 - sftp
 - forklift
 - filezilla
 - terminal
 - shell
 - xshell
 - telnet
 - bash
 - zsh
Installers: 
 - Architecture: "x64"
   InstallerUrl: https://cdn.netsarang.net/0ac7ea20/PortX-1.1.1-setup.exe
   InstallerSha256: fc80fe9bdb7f96bf4bfaea6910b713506f4e4f6e7433cd7827b2ddc250482038
   InstallerType: exe
   InstallerSwitches:
    Silent: /S
    SilentWithProgress: /S
PackageLocale: en-US    
ManifestType: singleton
ManifestVersion: 1.0.0