# Automatically updated by the winget bot at 2021/May/06
PackageIdentifier: Foxit.PhantomPDF
Publisher: Foxit
PackageName: PhantomPDF
PackageVersion: 11.0.0.49893
License: 2020 © Foxit Software Incorporated. All rights reserved.
InstallerType: exe
Moniker: FoxitPhantomPDF
Tags:
- PDF
- Foxit
ShortDescription: PhantomPDF is the PDF Editor that enables PDF document accessibility for people with disabilities who use assistive technology to have access to information.
PackageUrl: https://www.foxitsoftware.com/pdf-editor/
Installers:
- Architecture: x86
  InstallerUrl: https://www.foxitsoftware.com/downloads/latest.php?product=Foxit-PhantomPDF-Standard&platform=Windows&package_type=exe&language=L10N
  InstallerSha256: 961EFCAE536CA5C0EF013E552E2A49C611FF8CADF48401F41FEA7A425003F4F1
  InstallerSwitches:
    Silent: /silent
PackageLocale: en-US
ManifestType: singleton
ManifestVersion: 1.0.0
