# Automatically updated by the winget bot at 2021/May/21
PackageIdentifier: Spotify.Spotify
PackageVersion: latest
PackageName: Spotify
Publisher: Spotify AB
Moniker: spotify
License: Copyright © 2012 Spotify AB. All rights reserved.
Tags:
- Music
- Streaming
InstallerType: exe
ShortDescription: Spotify is a digital music service that gives you access to millions of songs.
PackageUrl: https://www.spotify.com
LicenseUrl: https://www.spotify.com/us/legal/end-user-agreement
Installers:
- Architecture: neutral
  InstallerUrl: https://download.scdn.co/SpotifySetup.exe
  InstallerSha256: 1E863C11493F77CA1A3BFC64D6F1D8A18BC128C9B36C48B7227BA8F416337E23
  InstallerSwitches:
    Silent: /Silent
    SilentWithProgress: /Silent
PackageLocale: en-US
ManifestType: singleton
ManifestVersion: 1.0.0
