# yaml-language-server: $schema=https://aka.ms/winget-manifest.singleton.1.0.0.schema.json
PackageIdentifier: CodecGuide.K-LiteCodecPackMega
Publisher: Codec Guide
PackageName: K-Lite Codec Pack Mega
PackageVersion: 16.2.0
License: Copyright 2004-2020, Codec Guide. All rights reserved.
LicenseUrl: https://www.codecguide.com/termsofuse.htm
Moniker: k-litecodecpackmega
Tags:
- video
- audio
- player
- mkv
- mpeg
- mp4
- multimedia
ShortDescription: CodecGuide.K-LiteCodecPackMega
Description: The K-Lite Codec Pack is a collection of DirectShow filters, VFW/ACM codecs, and tools. Codecs and DirectShow filters are needed for encoding and decoding audio and video formats. The K-Lite Codec Pack is designed as a user-friendly solution for playing all your audio and movie files. With the K-Lite Codec Pack you should be able to play all the popular audio and video formats and even several less common formats.
PackageUrl: https://www.codecguide.com/
Installers:
- Architecture: x86
  InstallerType: inno
  InstallerUrl: https://files3.codecguide.com/K-Lite_Codec_Pack_1620_Mega.exe
  InstallerSha256: 2AED8482C0D906A4E3C619A4B0C4AD867425B16DD98E0B550DE213681D5414BF
PackageLocale: en-US
ManifestType: singleton
ManifestVersion: 1.0.0

