# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.0.0.schema.json
PackageIdentifier: TeamViewer.TeamViewer
PackageVersion: 15.18.4
MinimumOSVersion: 10.0.0.0
InstallModes:
  - interactive
  - silent
  - silentWithProgress
Installers:
  - Architecture: x64
    InstallerType: nullsoft
    InstallerUrl: https://download.teamviewer.com/download/TeamViewer_Setup_x64.exe
    InstallerSha256: 99e8448d9d8b7fca578e7e0961a2841c31f709a2d0c829e77a9ae427cc5d5e0a
    Scope: machine
    InstallerLocale: en-US
    UpgradeBehavior: install
  - Architecture: x86
    InstallerType: nullsoft
    InstallerUrl: https://download.teamviewer.com/download/TeamViewer_Setup.exe
    InstallerSha256: 5c629ad39ab82edecad2122127d2cbbcb398cea35a54a976ffeecb8da2eb4af4
    Scope: machine
    InstallerLocale: en-US
    UpgradeBehavior: install
ManifestType: installer
ManifestVersion: 1.0.0
