# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.0.0.schema.json
PackageIdentifier: Ocenaudio.Ocenaudio
PackageVersion: "3.10.7"
Platform:
  - Windows.Desktop
InstallerType: nullsoft
Installers:
  - Architecture: x86
    InstallerUrl: https://www.ocenaudio.com/downloads/ocenaudio.exe?
    InstallerSha256: 491C1B6E1D12D51D4D1F368082320A05352AD51754EFE774F1481EBF050CDBAD
  - Architecture: x64
    InstallerUrl: https://www.ocenaudio.com/downloads/ocenaudio64.exe?
    InstallerSha256: DB4C56516497E190252170AA78F2D1DCA24CC69C4C9F9B5CB026AB17D066DD16
ManifestType: installer
ManifestVersion: 1.0.0
