# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultlocale.1.0.0.schema.json
PackageIdentifier: Ocenaudio.Ocenaudio
PackageVersion: "3.10.7"
PackageLocale: en-US
Publisher: ocenaudio Team
PublisherUrl: https://www.ocenaudio.com/
PackageName: ocenaudio
PackageUrl: https://www.ocenaudio.com/
License: Freeware, closed-source
Copyright: © 2009-2021 ocenaudio Team. All rights reserved.
ShortDescription: ocenaudio is a cross-platform, easy to use, fast and functional audio editor.
Tags:
  - music
  - audio
  - player
  - mp3
  - media
  - spectrum
  - spectrogram
ManifestType: defaultLocale
ManifestVersion: 1.0.0