# Automatically updated by the winget bot at 2021/May/24
PackageIdentifier: TopalaSoftwareSolutions.SIW
Publisher: Topala Software Solutions
PackageName: System Information for Windows
Moniker: siw
MinimumOSVersion: 6.1.0.0
PackageVersion: 2021.04.25.3
ShortDescription: System Information for Windows - Everything you want to know about your computer
License: Commercial
LicenseUrl: https://www.gtopala.com/agreement/
PackageUrl: https://www.gtopala.com/
Installers:
- Architecture: neutral
  InstallerUrl: https://siw64.com/download/siwtrial-setup.exe
  InstallerSha256: 7052DD4A4383B1C09C3082826AA4068018837328C666999143D662E2D05AE0D6
  InstallerType: inno
  InstallerSwitches:
    Silent: /VERYSILENT
    SilentWithProgress: /VERYSILENT
PackageLocale: en-US
ManifestType: singleton
ManifestVersion: 1.0.0
