# Automatically updated by the winget bot at 2021/May/24
PackageIdentifier: Malwarebytes.Malwarebytes
PackageVersion: 4.4.0.220
Installers:
- Architecture: neutral
  InstallerUrl: https://downloads.malwarebytes.com/file/mb4_offline
  InstallerSha256: 6162C2F57BAA38B08AC58175CF905F11D868A3C182104E0A0A5A299621AF0DB0
  Scope: machine
  InstallerType: exe
  InstallerSwitches:
    Custom: /SUPPRESSMSGBOXES /NORESTART
    Silent: /VERYSILENT
    SilentWithProgress: /VERYSILENT
  InstallModes:
  - "interactive"
  - "silent"
  - "silentWithProgress"
  UpgradeBehavior: install
ManifestType: installer
ManifestVersion: 1.0.0
