# Automatically updated by the winget bot at 2021/May/13
PackageIdentifier: KCSoftwares.SUMo
PackageVersion: 5.12.13.490
PackageName: SUMo
Publisher: KC Softwares
License: Copyright (c) KC Softwares
Tags:
- software
- update
- monitor
ShortDescription: SUMo (Software Update Monitor) keeps your PC up-to-date & safe by using the most recent version of your favorite software !
PackageUrl: https://kcsoftwares.com/?sumo
Installers:
- Architecture: x64
  InstallerUrl: https://kcsoftwares.com/files/sumo_lite.exe
  InstallerSha256: FFE0946C91433128D5675EAD92EB0CB395629094B9D6E6FF75E22641769A920A
  InstallerType: inno
PackageLocale: en-US
ManifestType: singleton
ManifestVersion: 1.0.0
