# Automatically updated by the winget bot at 2021/May/21
PackageIdentifier: SFLinux.Jami
PackageVersion: 1.0.7811.37362
PackageLocale: en-US
Publisher: Savoir-faire Linux
PublisherUrl: https://savoirfairelinux.com/
PublisherSupportUrl: https://savoirfairelinux.com/contact
PrivacyUrl: https://jami.net/privacy-policy/
PackageName: Jami
PackageUrl: https://jami.net/
License: GPL-3.0-or-later
LicenseUrl: https://git.jami.net/savoirfairelinux/ring-project/raw/master/COPYING
ShortDescription: A free and universal communication platform which preserves the user's privacy and freedoms.
Moniker: jami
Tags:
- instant messenger
- communication
- privacy
- freedom
- user privacy
ManifestType: defaultLocale
ManifestVersion: 1.0.0
