# Automatically updated by the winget bot at 2021/May/21
PackageIdentifier: SFLinux.Jami
PackageVersion: 1.0.7811.37362
MinimumOSVersion: 10.0.0.0
InstallModes:
- interactive
- silent
- silentWithProgress
Installers:
- Architecture: x64
  InstallerType: msi
  InstallerUrl: https://dl.jami.net/windows/jami.release.x64.msi
  InstallerSha256: BF8DB99FE366284F67055AC2CAA22EF52D0335C1D0C2E3B492BEFCD1873F04D2
  Scope: machine
  InstallerLocale: en-US
  UpgradeBehavior: install
ManifestType: installer
ManifestVersion: 1.0.0
