# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.0.0.schema.json
PackageIdentifier: LogMeIn.LastPass
PackageVersion: 4.72.0.2105
MinimumOSVersion: 10.0.0.0
InstallModes:
  - interactive
  - silent
  - silentWithProgress
Installers:
  - Architecture: x86
    InstallerType: msi
    InstallerUrl: https://download.cloud.lastpass.com/windows_installer/LastPassInstaller.msi
    InstallerSha256: D996BDDBA0BF728E77171FF724622FCA6D3A3ED522E242841E28A6BEF4D3FBCF
    ProductCode: "{BFBE9988-C364-4B90-BB90-A3C43ED6C658}"
    Scope: machine
    InstallerLocale: en-US
    UpgradeBehavior: install
ManifestType: installer
ManifestVersion: 1.0.0
