# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.0.0.schema.json
PackageIdentifier: Google.ChromeBeta
PackageVersion: 68.94.77
MinimumOSVersion: 10.0.0.0
FileExtensions:
  - html
  - htm
  - url
Protocols:
  - http
  - https
InstallModes:
  - interactive
  - silent
  - silentWithProgress
Installers:
  - Architecture: x64
    InstallerType: msi
    InstallerUrl: https://dl.google.com/tag/s/dl/chrome/install/beta/googlechromebetastandaloneenterprise64.msi
    InstallerSha256: 7F660E5393D7B9DBDD995DE9AFB87D08DB2A680BC8C9208A4ADAEACE113AFFF5
    ProductCode: "{FDCBB01C-3E54-32C9-B1B2-244808C37634}"
    Scope: machine
    InstallerLocale: en-US
    UpgradeBehavior: install
  - Architecture: x86
    InstallerType: msi
    InstallerUrl: https://dl.google.com/tag/s/dl/chrome/install/beta/googlechromebetastandaloneenterprise.msi
    InstallerSha256: FCDB48A56AE7BC5BC0C7D47DFFBE0CFFA8E67D91717A6BA61CED7CF117DFD10B
    ProductCode: "{C1EE7F70-F271-39CB-A2A3-81D5CA49186A}"
    Scope: machine
    InstallerLocale: en-US
    UpgradeBehavior: install
ManifestType: installer
ManifestVersion: 1.0.0
