# Automatically updated by the winget bot at 2021/May/25
PackageIdentifier: Autodesk.Fusion360
PackageVersion: latest
PackageName: Fusion 360
Publisher: Autodesk
License: Copyright (c) Autodesk Inc.
ShortDescription: Integrated CAD, CAM, and PCB software
PackageUrl: https://www.autodesk.com/products/fusion-360/overview
Installers:
- Architecture: x86
  InstallerUrl: https://dl.appstreaming.autodesk.com/production/installers/Fusion%20360%20Admin%20Install.exe
  InstallerSha256: CD3E961B3719C26167321127E8FB7821DA58B695B4025437F2CC7AD79C6A50B5
  InstallerType: exe
  InstallerSwitches:
    Silent: --quiet
    SilentWithProgress: --quiet
PackageLocale: en-US
ManifestType: singleton
ManifestVersion: 1.0.0
