# Automatically updated by the winget bot at 2021/May/26
PackageIdentifier: SmartSoft.SmartFTP
PackageVersion: 9.0.2850.0
MinimumOSVersion: 10.0.0.0
InstallModes:
- interactive
- silent
- silentWithProgress
Installers:
- Architecture: x64
  InstallerType: msi
  InstallerUrl: https://www.smartftp.com/get/SmartFTP64.msi
  InstallerSha256: 107E9790D785F45240F0D3AAAEA0D60C6CA95C59CAC36E4FC4E38EB2357595C4
  ProductCode: "{958D61CE-AB22-47D7-9E20-13DA35AAF5E5}"
  Scope: machine
  InstallerLocale: en-US
  UpgradeBehavior: install
ManifestType: installer
ManifestVersion: 1.0.0
