PackageIdentifier: "alibaba.dingtalk"
PackageVersion: "6.0.15.5171263"
PackageLocale: "zh-CN"
Publisher: "alibaba"
PackageName: "dingtalk"
License: "Copyright 2014-2020, Alibaba Inc."
ShortDescription: "Dingtalk, make work and study easy"
Moniker: dingding
Installers: 
 - Architecture: "x86"
   InstallerType: "nullsoft"
   InstallerUrl: "https://www.dingtalk.com/win/d/"
   InstallerSha256: 654F897D57064D588D8FE13060D1419F1B100E731D4CCD60A7774BEB8C1B8A73
   InstallerSuccessCodes:
     - 1223
ManifestType: "singleton"
ManifestVersion: "1.0.0"
